
// Was generated by REST Plugin Wizard
def procName = 'Deploy Assignment'
def stepName = 'deploy assignment'
procedure procName, description: 'Deploys assignment', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('deploy assignment');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
