
// Was generated by REST Plugin Wizard
def procName = 'Create Release'
def stepName = 'create release'
procedure procName, description: 'Generates Tasks in Assignment', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('create release');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
