
// Was generated by REST Plugin Wizard
def procName = 'Create Assignment'
def stepName = 'create assignment'
procedure procName, description: 'Creates an Assignment', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('create assignment');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
