
// Was generated by REST Plugin Wizard
def procName = 'Generate Events'
def stepName = 'generate events'
procedure procName, description: 'Generate events JSON for callbacks', {

    step stepName,
        command: new File(pluginDir, "dsl/procedures/GenerateEvents/steps/generateEvents.pl").text,
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
