
// Was generated by REST Plugin Wizard
def procName = 'Get Set Information'
def stepName = 'get set information'
procedure procName, description: 'Gets Set information', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('get set information');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
