
// Was generated by REST Plugin Wizard
def procName = 'Load Task'
def stepName = 'Load Task'
procedure procName, description: 'Loads a Task for the specified Assignment', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('Load Task');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
